### ISSUE TITLE
Feature request - shorten displayed paths to files

### ISSUE THREAD

**Issue by Parker7123** [AlexGirardDev/HarpoonIJ#11] opened 2024-02-02 21:30 UTC
What about shortening paths to files shown in harpoon dialog? When I add files in nested directories many times it happens that file name goes past window box. I'm not sure how it is handled in original plugin though. Pic included.

![image](https://github.com/AlexGirardDev/HarpoonIJ/assets/38889760/0c62451a-dcec-4338-bd49-ee7bec612eed)

**Comment by AlexGirardDev** [comment] 2024-02-03 04:18
hmmm looks like he didn'th andle this very well either
![image](https://github.com/AlexGirardDev/HarpoonIJ/assets/37006998/e6ccc17c-77af-46f6-ad96-d663ee9729a6)

you can increase the width of the modal in the settings if that is a good enough fix for you.

if not i might be able to figure out a nicer solution

**Comment by Parker7123** [comment] 2024-02-04 14:42
Found out that original harpoon handles this case somehow https://github.com/ThePrimeagen/harpoon/issues/345

**Comment by AlexGirardDev** [comment] 2024-02-04 17:19
So this is actualy refering to removing everything before your project root which I am actualy doing, thats what the .../ is at the start of your file paths 

The problem is that it seems like Java / kotlith paths put code realy deep in a directory structure so you get the problem you are running into.

![image](https://github.com/AlexGirardDev/HarpoonIJ/assets/37006998/f314e57d-e50d-4c74-8697-6caf8cfcebf0)
Here is an example from my harpoon proect. 
The AppsettingsConfigurable.java file is actualy just 6 folders deep in my project so i am showing that entire path
The Build.Gradle.kts is acutaly in the project root so its path is way shorten
Then i alse added a file from a different project and it is showing the absolute path

**Comment by AlexGirardDev** [comment] 2024-02-17 01:03
there is some discussions around something similiar to this at #13, so i'm going to close this issue

**Closed as completed by AlexGirardDev** 2024-02-17 01:03 UTC
